In [9]:
import torch.nn as nn
import torch
import torch.nn.functional as F
import torch.optim as optim

class SimpleNet(nn.Module):
    def __init__(self, input_dim = 16, hidden_size=64):
        super().__init__()
        self.fc1 = nn.Linear(input_dim, hidden_size)
        self.ac1 = nn.ReLU()
        self.fc2 = nn.Linear(hidden_size, 1)

    def forward(self, x):
        x = self.fc1(x)
        x = self.ac1(x)
        x = self.fc2(x)
        return x

x = torch.randn(8, 16)
y = torch.randn(8, 1)


model = SimpleNet()
optimizer = optim.Adam(model.parameters(), lr=1e-2)
for epoch in range(50):
    print(f"Epoch {epoch}")
    pred = model(x)

    loss_func = nn.MSELoss()
    loss = loss_func(pred, y)


    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    

    print(loss.item())

print("训练完成")

Epoch 0
0.4636911451816559
Epoch 1
0.28125888109207153
Epoch 2
0.1711694300174713
Epoch 3
0.10877498984336853
Epoch 4
0.06876680999994278
Epoch 5
0.040339939296245575
Epoch 6
0.023386701941490173
Epoch 7
0.020348817110061646
Epoch 8
0.025137608870863914
Epoch 9
0.028335152193903923
Epoch 10
0.026895463466644287
Epoch 11
0.02126469649374485
Epoch 12
0.01519602071493864
Epoch 13
0.012432684190571308
Epoch 14
0.012595823965966702
Epoch 15
0.012746130116283894
Epoch 16
0.01163665484637022
Epoch 17
0.009896839037537575
Epoch 18
0.008315622806549072
Epoch 19
0.006962415296584368
Epoch 20
0.005467585753649473
Epoch 21
0.0038224938325583935
Epoch 22
0.002721665659919381
Epoch 23
0.0028663163539022207
Epoch 24
0.0041361539624631405
Epoch 25
0.005549537017941475
Epoch 26
0.00605482142418623
Epoch 27
0.005344466771930456
Epoch 28
0.003871549852192402
Epoch 29
0.0023737018927931786
Epoch 30
0.0013070752611383796
Epoch 31
0.0007371194078586996
Epoch 32
0.0005528876790776849
Epoch 33
0.0006769050960

In [ ]:
class miniPolicyNet(nn.Module):
    def __init__(self, in_dim = 4, hidden_dim = 8):
        super().__init__()
        self.fc1 = nn.Linear(in_dim, hidden_dim)
        self.act1 = nn.ReLU()
        self.ac = nn.Linear(hidden_dim, 2)
        self.act2 = nn.Softmax(dim=-1)

    def forward(self, x):
        x = self.fc1(x)
        x = self.act1(x)
        x = self.ac(x)
        x = self.act2(x)
        return x
    

model = miniPolicyNet()
optimizer = optim.Adam(model.parameters(), lr=1e-2)  # new environment
state = torch.randn(1, 4)

for epoch in range(100):
    print(f"epoch {epoch}")
    pred = model(state) # size [batch_size, 2]
    
    dist = torch.distributions.Categorical(pred)
    action = dist.sample()
    # print(type(action), action.item())
    log_prob = dist.log_prob(action)
    if action.item() == 0:
        reward = 1.0
    else:
        reward = -1.0
    optimizer.zero_grad()
    loss = -log_prob * reward
    loss.backward()
    optimizer.step()

    print(loss.item())

print("training complete")


epoch 0
tensor([[0.5253, 0.4747]], grad_fn=<SoftmaxBackward0>)
0.6436929106712341
epoch 1
tensor([[0.5499, 0.4501]], grad_fn=<SoftmaxBackward0>)
0.5980030298233032
epoch 2
tensor([[0.5742, 0.4258]], grad_fn=<SoftmaxBackward0>)
-0.8537091612815857
epoch 3
tensor([[0.5981, 0.4019]], grad_fn=<SoftmaxBackward0>)
0.5139885544776917
epoch 4
tensor([[0.6170, 0.3830]], grad_fn=<SoftmaxBackward0>)
-0.9597440958023071
epoch 5
tensor([[0.6355, 0.3645]], grad_fn=<SoftmaxBackward0>)
0.4533872604370117
epoch 6
tensor([[0.6537, 0.3463]], grad_fn=<SoftmaxBackward0>)
0.42517825961112976
epoch 7
tensor([[0.6715, 0.3285]], grad_fn=<SoftmaxBackward0>)
0.3982182443141937
epoch 8
tensor([[0.6890, 0.3110]], grad_fn=<SoftmaxBackward0>)
0.37258070707321167
epoch 9
tensor([[0.7063, 0.2937]], grad_fn=<SoftmaxBackward0>)
0.3476469814777374
epoch 10
tensor([[0.7236, 0.2764]], grad_fn=<SoftmaxBackward0>)
0.32349029183387756
epoch 11
tensor([[0.7407, 0.2593]], grad_fn=<SoftmaxBackward0>)
0.30018582940101624
epoch 12

In [ ]:
class miniPolicyNet(nn.Module):
    def __init__(self, in_dim = 4, hidden_dim = 8):
        super().__init__()
        self.fc1 = nn.Linear(in_dim, hidden_dim)
        self.act1 = nn.ReLU()
        self.ac = nn.Linear(hidden_dim, 2)
        self.act2 = nn.Softmax(dim=-1)

    def forward(self, x):
        x = self.fc1(x)
        x = self.act1(x)
        x = self.ac(x)
        x = self.act2(x)
        return x

model = miniPolicyNet()
optimizer = optim.Adam(model.parameters(), lr=1e-2)  # new environment


for epoch in range(200):
    print(f"epoch {epoch}")
    state = torch.randn(1, 4)
      # state action
    pred = model(state) ## size [batch_size, 2] 
    print(state[0][0].item(), pred.detach())
    dist = torch.distributions.Categorical(pred)
    action = dist.sample()
    print(action)
    # print(type(action), action.item())
    log_prob = dist.log_prob(action)
    if state[0][0] > 0:
        if action.item() == 0:
            reward = 1.0
        else:
            reward = -1.0
    else:
        if action.item() == 0:
            reward = -1.0
        else:
            reward = 1.0
    optimizer.zero_grad()
    loss = -log_prob * reward
    loss.backward()
    optimizer.step()

    print(loss.item())

print("training complete")


epoch 0
0.47480037808418274 tensor([[0.5327, 0.4673]])
tensor([0])
0.6297884583473206
epoch 1
0.12436770647764206 tensor([[0.6264, 0.3736]])
tensor([1])
-0.9846051931381226
epoch 2
1.1669373512268066 tensor([[0.6310, 0.3690]])
tensor([0])
0.4604502022266388
epoch 3
1.5359002351760864 tensor([[0.6736, 0.3264]])
tensor([0])
0.3950859606266022
epoch 4
-0.3276667594909668 tensor([[0.7198, 0.2802]])
tensor([0])
-0.3288441598415375
epoch 5
0.8381727933883667 tensor([[0.6735, 0.3265]])
tensor([1])
-1.1194287538528442
epoch 6
1.62179434299469 tensor([[0.6298, 0.3702]])
tensor([0])
0.46236228942871094
epoch 7
-0.46988925337791443 tensor([[0.6846, 0.3154]])
tensor([1])
1.1540447473526
epoch 8
-0.9047601222991943 tensor([[0.5303, 0.4697]])
tensor([0])
-0.634400486946106
epoch 9
-0.0802520364522934 tensor([[0.6777, 0.3223]])
tensor([0])
-0.38906317949295044
epoch 10
-0.7332592606544495 tensor([[0.6628, 0.3372]])
tensor([1])
1.0871833562850952
epoch 11
-0.7195754051208496 tensor([[0.5498, 0.4502]])

In [ ]:
class miniPolicyNet(nn.Module):
    def __init__(self, in_dim = 4, hidden_dim = 8):
        super().__init__()
        self.fc1 = nn.Linear(in_dim, hidden_dim)
        self.act1 = nn.ReLU()
        self.ac = nn.Linear(hidden_dim, 2)
        self.act2 = nn.Softmax(dim=-1)

    def forward(self, x):
        x = self.fc1(x)
        x = self.act1(x)
        x = self.ac(x)
        x = self.act2(x)
        return x
    
class miniValueNet(nn.Module):
    def __init__(self, in_dim = 4, hidden_dim = 8):
        super().__init__()
        self.fc1 = nn.Linear(in_dim, hidden_dim)
        self.act1 = nn.ReLU()
        self.fc2 = nn.Linear(hidden_dim, 1)
    
    def forward(self, x):
        return self.fc2(self.act1(self.fc1(x)))

model = miniPolicyNet()
optimizer = optim.Adam(model.parameters(), lr=1e-2)  # new environment

v_model = miniValueNet()
v_optimizer = optim.Adam(v_model.parameters(), lr=1e-2)

v_loss_func = nn.MSELoss()  # value loss function

for epoch in range(200):
    print(f"epoch {epoch}")
    state = torch.randn(1, 4)
    # state action
    pred = model(state) ## size [batch_size, 2] 
    # print(state[0][0].item(), pred.detach())
    dist = torch.distributions.Categorical(pred)
    action = dist.sample()
    v_state = v_model(state)
    # print(type(action), action.item())
    log_prob = dist.log_prob(action)
    if state[0][0] > 0:
        if action.item() == 0:
            reward = 1.0
        else:
            reward = -1.0
    else:
        if action.item() == 0: # 
            reward = -1.0
        else:
            reward = 1.0
    
    optimizer.zero_grad()
    v_optimizer.zero_grad()
    loss = -log_prob * (reward - v_state.detach())
    v_loss = v_loss_func(v_state, torch.tensor([[reward]]))

    loss = loss + v_loss
    loss.backward()
    optimizer.step()
    v_optimizer.step()
    
    print(loss.item())

print("training complete")


epoch 0
0.019458502531051636
epoch 1
0.3948027789592743
epoch 2
-0.1542869508266449
epoch 3
-0.08920621871948242
epoch 4
3.0593512058258057
epoch 5
-0.18710577487945557
epoch 6
3.586364984512329
epoch 7
-0.025406330823898315
epoch 8
6.376319408416748
epoch 9
4.366001605987549
epoch 10
-0.2059737592935562
epoch 11
-0.23544985055923462
epoch 12
-0.06758461892604828
epoch 13
2.946211814880371
epoch 14
2.105363130569458
epoch 15
-0.09580062329769135
epoch 16
2.5796608924865723
epoch 17
2.921428680419922
epoch 18
-0.08562159538269043
epoch 19
2.2586464881896973
epoch 20
2.1976211071014404
epoch 21
-0.1286219358444214
epoch 22
-0.11949488520622253
epoch 23
-0.08077606558799744
epoch 24
1.9759690761566162
epoch 25
0.08720850944519043
epoch 26
0.13895520567893982
epoch 27
3.1245481967926025
epoch 28
0.029633671045303345
epoch 29
-0.3636350631713867
epoch 30
1.9293172359466553
epoch 31
3.1597723960876465
epoch 32
2.5329089164733887
epoch 33
0.01017141342163086
epoch 34
2.033111572265625
epoch 3

In [1]:
from dotenv import load_dotenv
import os

api_key = os.getenv("SWANLAB_KEY")
print(api_key)

FD1UV1wgT0yOnkP30rdGd


In [2]:
import os

print(os.getcwd())

d:\VsCodeProj\RL


In [ ]:
"""
转换数据格式
"""
import json


def convert_dialogue(input_file, output_file):
    """
    转换对话格式
    
    输入：带attrs的原始对话数据（JSON数组）
    输出：Qwen格式的多轮对话（JSONL，每行一条）
    """
    with open(input_file, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    with open(output_file, 'w', encoding='utf-8') as fout:
        for dialogue in data:
            messages = dialogue.get("messages", [])
            
            conversations = []
            
            # 遍历每条消息
            cnt = 0
            for msg in messages:
                message_text = msg.get("message", "").strip()
                
                if not message_text:
                    continue
                
                # 判断role：有attrs的是assistant，没有的是user
                if cnt % 2 == 1:
                    role = "assistant"
                else:
                    role = "user"
                
                conversations.append({
                    "role": role,
                    "content": message_text
                })
                cnt += 1
            output_sample = {
                "conversations": conversations
            }
            fout.write(json.dumps(output_sample, ensure_ascii=False) + '\n')


if __name__ == "__main__":
    # 输入输出文件路径
    input_file = r"d:/VsCodeProj/RL/SFT/film/test.json"
    output_file = "d:/VsCodeProj/RL/film/sft_test.json"
    
    
    convert_dialogue(input_file, output_file)
    
    print("输出样本预览（前5条）：")
    with open(output_file, 'r', encoding='utf-8') as f:
        for idx, line in enumerate(f):
            if idx >= 5:
                break
            data = json.loads(line)
            print(f"\n【第{idx+1}条】")
            for conv in data["conversations"]:
                print(conv)


输出样本预览（前5条）：

【第1条】
{'role': 'user', 'content': '看过《我是山姆》吗？'}
{'role': 'assistant', 'content': '是的，它是2001年12月28日上映的，很感人的电影。'}
{'role': 'user', 'content': '是的，是一部很好看的家庭，亲情剧，我记得片长也很长的。'}
{'role': 'assistant', 'content': '是的132分钟，你就准备好哭吧。'}
{'role': 'user', 'content': '电影的票房怎么样啊？'}
{'role': 'assistant', 'content': '这不清楚，但我知道它获得了2002年青年艺术家奖等诸多奖项，以及2002年奥斯卡美国电影学院奖等多项奖项提名。'}
{'role': 'user', 'content': '导演是谁啊，这么会选题材。'}
{'role': 'assistant', 'content': '导演是杰茜·尼尔森，他选演员的眼光很出独到。'}
{'role': 'user', 'content': '是的，西恩·潘就演的很好。'}
{'role': 'assistant', 'content': '嗯，他曾获得55届威尼斯国际电影节最佳男演员、60届威尼斯国际电影节最佳男演员。'}
{'role': 'user', 'content': '还有第76届奥斯卡金像奖最佳男主角、第81届奥斯卡金像奖最佳男主角。'}
{'role': 'assistant', 'content': '以及美国电影金球奖最佳男主角奖，他有这么多的奖项，知道他的第一个奖项的作品是什么吗？'}
{'role': 'user', 'content': '知道啊，是1996年，在第46届柏林电影节中凭借监狱片《死囚漫步》获得人生第一个最佳男演员奖。'}
{'role': 'assistant', 'content': '这么看他是学表演的？'}
{'role': 'user', 'content': '是的，他是耶鲁大学表演系的。'}
{'role': 'assistant', 'content': '他是一名杰出的演员，导演。'}
{'role': 'user', 'content': '我听说他的第